contact_links:
  - name: âš ï¸ Application issue
    url: https://github.com/komikku-app/anikku/issues/new/choose
    about: Issues and requests about the app itself should be opened in the Anikku repository instead
  - name: ğŸ“¦ Anikku extensions
    url: https://anikku-app.github.io/extensions
    about: List of all available extensions with download links
  - name: ğŸ–¥ï¸ Anikku website
    url: https://anikku-app.github.io/help/
    about: Guides, troubleshooting, and answers to common questions
