name: Merge Aniyomi

on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch: # Manual dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-merge:
    name: Merge Aniyomi
    if: github.repository == 'anikku-app/anikku-app.github.io'
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merging
        run: |
          git remote add aniyomi https://github.com/aniyomiorg/aniyomi-website.git
          git fetch aniyomi
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git merge -S --no-edit aniyomi/master

      - name: Push to repo
        run: |
          git push
